INSERT INTO USER_INFO (MOBILE_NO,NAME,PASSWORD,EMAIL) VALUES (9493048990, 'gmr','password', 'gmr@gmail.com');
INSERT INTO USER_INFO (MOBILE_NO,NAME,PASSWORD,EMAIL) VALUES (9493048991, 'sam','password', 'sam@yahoo.com');
INSERT INTO USER_INFO (MOBILE_NO,NAME,PASSWORD,EMAIL) VALUES (9493048992, 'abdul','password', 'abdul@gmail.com');
INSERT INTO USER_INFO (MOBILE_NO,NAME,PASSWORD,EMAIL) VALUES (9493048993, 'tony','password', 'tony@gmail.com');